# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_c_compilerclang
    - CONFIG=osx_c_compilertoolchain_c

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "x6VUYMxw5AFrKDiqdxs+YII6JWPjoJf4R+93XfQAc2eBgNE+YAFGWY6+ETxxwG8GFHBqU/dkM6j3gyyjxa6gnOfdG2Ns/NMUzOkR+s6Cf6aNKPNzpIw1LERatu0pHjVk0mKX7BZ+Rz1Uz29/qaYVMAdIS/hQfBbJb+0D9iPy1JB4bVL4OxlTRGWxEBoAUdlikAkXhjSd6suL62mrETzhvG8W/9C8eh8DRKQVEUKY+XQW1mFV5jeXBrVz5QRsViASkUC1e6KZ5+m5xTkr/SzFKCMtSUkZM5R9Wg0a17iN7tdrzHmzymaA814Zn4ua3yDHIInWsP3/Fa+fdYDhKYwjIR/7OZtlLt/8Kr5RkHIeAxsx0f7y9mD1vraq0ZKTiGmYVhHUNuMNxmpxxPtv6wwcNrrNdfe1rH5V5bA0AdYHAuaCy4KArQfTwPTO9H6t13BpSJHPUM6PqYzjIPM2xMdYxzCtfx7xoLJ/w6ElYXnpFlVKQPPpvWPZcDHyEtAJ5wqfMcUN93YtHOuWVeGzyZN5x28N/hUQCGwZXhiGzNYzQLJX4DU1JyK2pPgxEea10EHvDM8cSpcSd1OD/EZbIHpSq+ZQwj+0Qm5U4bsw8F0CrobXGUfM/Xw+djSCbs6oAgFAlQt6iKoTSwhNVfI7cJlp3XpeBGX05lnXtg0AIFPryDk="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml