appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: x6VUYMxw5AFrKDiqdxs+YII6JWPjoJf4R+93XfQAc2eBgNE+YAFGWY6+ETxxwG8GFHBqU/dkM6j3gyyjxa6gnOfdG2Ns/NMUzOkR+s6Cf6aNKPNzpIw1LERatu0pHjVk0mKX7BZ+Rz1Uz29/qaYVMAdIS/hQfBbJb+0D9iPy1JB4bVL4OxlTRGWxEBoAUdlikAkXhjSd6suL62mrETzhvG8W/9C8eh8DRKQVEUKY+XQW1mFV5jeXBrVz5QRsViASkUC1e6KZ5+m5xTkr/SzFKCMtSUkZM5R9Wg0a17iN7tdrzHmzymaA814Zn4ua3yDHIInWsP3/Fa+fdYDhKYwjIR/7OZtlLt/8Kr5RkHIeAxsx0f7y9mD1vraq0ZKTiGmYVhHUNuMNxmpxxPtv6wwcNrrNdfe1rH5V5bA0AdYHAuaCy4KArQfTwPTO9H6t13BpSJHPUM6PqYzjIPM2xMdYxzCtfx7xoLJ/w6ElYXnpFlVKQPPpvWPZcDHyEtAJ5wqfMcUN93YtHOuWVeGzyZN5x28N/hUQCGwZXhiGzNYzQLJX4DU1JyK2pPgxEea10EHvDM8cSpcSd1OD/EZbIHpSq+ZQwj+0Qm5U4bsw8F0CrobXGUfM/Xw+djSCbs6oAgFAlQt6iKoTSwhNVfI7cJlp3XpeBGX05lnXtg0AIFPryDk=}
